[package]
name = "umber-export"
description = "Umber export: template/preset engine and image encoders"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
exr = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
png = "0.17"
ag-psd = "0.3.0"
umber-graph = { workspace = true }
