[package]
name = "umber-gpu"
description = "Umber GPU layer: wgpu device context, render graph, tile pool, shaders"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
log = { workspace = true }
umber-mesh = { workspace = true }
glam = { workspace = true }
wgpu = { workspace = true }
egui-wgpu = { workspace = true }
epaint = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true, optional = true }
profiling = { workspace = true }

[features]
gpu = ["pollster"]
